# Permalinks
permalink:           pretty

# Setup
title:               Yousef Alotaibi
tagline:             Data Science Blog
url:                 http://thiabi.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Yousef Alotaibi
  url:               https://twitter.com/zaglamir
  email:             althiabi@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/thiabi

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
